//! Shell environment export for Codex CLI in terminal sessions.

use std::fs::{self, OpenOptions};
use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::secrets::{self, supported_env_keys};

const ENV_FILE_NAME: &str = "env.sh";
const ZSHRC_MARKER: &str = "# CrabBridge desktop env";

pub fn env_script_path(config_dir: &Path) -> PathBuf {
    config_dir.join(ENV_FILE_NAME)
}

pub fn write_env_script(config_dir: &Path) -> Result<PathBuf> {
    fs::create_dir_all(config_dir)
        .with_context(|| format!("failed to create {}", config_dir.display()))?;

    let path = env_script_path(config_dir);
    let mut body = String::from(
        "# Generated by CrabBridge desktop — source this file from your shell.\n\
         # Example: add to ~/.zshrc:\n\
         #   [ -f \"$HOME/.config/crabbridge/env.sh\" ] && source \"$HOME/.config/crabbridge/env.sh\"\n\
         \n",
    );

    let mut wrote_any = false;
    for env_key in supported_env_keys() {
        if let Some(value) = secrets::resolve_env_value(env_key)? {
            body.push_str(&format!(
                "export {env_key}='{}'\n",
                shell_escape_single(&value)
            ));
            wrote_any = true;
        }
    }

    if !wrote_any {
        for env_key in supported_env_keys() {
            body.push_str(&format!("# export {env_key}=<your-key>\n"));
        }
    }

    fs::write(&path, body).with_context(|| format!("failed to write {}", path.display()))?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&path)
            .with_context(|| format!("failed to stat {}", path.display()))?
            .permissions();
        perms.set_mode(0o600);
        fs::set_permissions(&path, perms)
            .with_context(|| format!("failed to chmod {}", path.display()))?;
    }

    Ok(path)
}

pub fn install_zsh_hook(config_dir: &Path) -> Result<String> {
    let home = std::env::var("HOME").context("HOME is not set")?;
    let zshrc = PathBuf::from(home).join(".zshrc");
    let env_path = env_script_path(config_dir);
    let hook = format!(
        "{ZSHRC_MARKER}\n[ -f \"{path}\" ] && source \"{path}\"\n",
        path = env_path.display()
    );

    if zshrc.is_file() {
        let existing = fs::read_to_string(&zshrc)
            .with_context(|| format!("failed to read {}", zshrc.display()))?;
        if existing.contains(ZSHRC_MARKER) {
            return Ok(format!(
                "Shell hook already present in {}",
                zshrc.display()
            ));
        }
        let mut file = OpenOptions::new()
            .append(true)
            .open(&zshrc)
            .with_context(|| format!("failed to open {}", zshrc.display()))?;
        writeln!(file, "\n{hook}")
            .with_context(|| format!("failed to append to {}", zshrc.display()))?;
    } else {
        fs::write(&zshrc, format!("{hook}\n"))
            .with_context(|| format!("failed to write {}", zshrc.display()))?;
    }

    Ok(format!(
        "Added CrabBridge env hook to {} — run `source ~/.zshrc` in open terminals",
        zshrc.display()
    ))
}

pub fn codex_usage_hint(bind_addr: &str) -> String {
    format!(
        "CrabBridge MVP is ready.\n\n\
         1. Start Codex in the terminal where DEEPSEEK_API_KEY is already set\n\
         2. Codex uses ~/.codex/config.toml written by setup\n\
         3. Bridge listens at http://{bind_addr}\n\
         4. Admin dashboard: http://{bind_addr}/admin\n\n\
         Providers:\n\
         - DeepSeek: http://{bind_addr}/deepseek/v1\n\
         - Kimi:     http://{bind_addr}/kimi/v1"
    )
}

fn shell_escape_single(value: &str) -> String {
    value.replace('\'', "'\"'\"'")
}
